r"""把 Spica 的两张引擎常量表导出成前端的 TS 模块。

  spica_wtab.json     100 张权重表 x 25 个 tap(索引 0 是平坦区那张)
  spica_gaincfg.json  512 项分类 LUT,只有前 256 项会被查到(bit8 折叠过)

这两张表是**算子自己的形状**,不随拍摄参数变,所以和锐化的核一样放前端,
不走 profile。随 profile 走的只有 amount 和 isoGain(见 sony/spica.py)。

用法(Windows 的 python,读的是本目录下两个 json):
    python spica_export_tables.py
"""
import json
import os

SCR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(SCR, "..", "..", "apps", "web", "src", "rendering", "spica-tables.ts")
NTAP, NTABLE, NCODE = 25, 100, 256

HEADER = '''/**
 * Sony Spica's two constant tables, lifted out of Edit.exe 4.0.00.10311.
 *
 * The classifier turns a 9-point local binary pattern into one of 100 weight
 * tables plus a mirroring; these are that mapping and those tables. They are
 * the operator's own shape rather than anything per-shot, so they live here
 * beside sharpening's kernel — only `amount` and `isoGain` travel on the
 * profile (worker sony/spica.py).
 *
 * Generated by sony_repro/tools/spica_export_tables.py. Do not hand-edit.
 * Reproduces the engine bit-for-bit over 8.1M of its own pixels
 * (sony_repro/PIPELINE.md 7.11.4.9).
 */

/** Taps per table: a radius-3 diamond, |dy| + |dx| <= 3, row-major. */
export const SPICA_TAP_COUNT = %(ntap)d;
/** Weight tables in the family, indexed 0..99 by the classifier. */
export const SPICA_TABLE_COUNT = %(ntable)d;
/** Folded pattern codes: 9 bits collapse to 8, so the LUT is 256 long. */
export const SPICA_CODE_COUNT = %(ncode)d;
/**
 * What the weights are normalised to. Every table's 25 taps sum to exactly
 * this, so the filter is unity gain on a flat patch and `S - 512 * centre` is
 * a pure detail term.
 */
export const SPICA_WEIGHT_SUM = 512;

/**
 * The tables, row-major: table `i` occupies `[i * 25, i * 25 + 25)`.
 *
 * Table 0 is the isotropic one the engine takes whenever the local range falls
 * under its threshold, without running the classifier at all.
 */
export const SPICA_WEIGHTS = new Int16Array([
%(weights)s
]);

/**
 * Pattern code -> `(table, dx, dy)`, three entries per code.
 *
 * `dx`/`dy` are each +-1 and mirror the *sampling grid*, not the table: two
 * codes that are mirror images share a table and differ only in how the
 * diamond is read. That is what collapses 512 codes onto 100 tables.
 */
export const SPICA_LUT = new Int8Array([
%(lut)s
]);
'''


def rows(flat, per_row, width):
    out = []
    for i in range(0, len(flat), per_row):
        out.append("  " + ", ".join(f"{v:{width}d}" for v in flat[i:i + per_row]) + ",")
    return "\n".join(out).rstrip(",")


def main():
    with open(os.path.join(SCR, "spica_wtab.json"), encoding="utf-8") as f:
        tables = json.load(f)["tables"]
    with open(os.path.join(SCR, "spica_gaincfg.json"), encoding="utf-8") as f:
        lut = json.load(f)["lut"]

    missing = [i for i in range(NTABLE) if str(i) not in tables]
    if missing:
        raise SystemExit(f"权重表缺 {missing} —— spica_wtab.py 的判据又把 padding 当条件了?")

    weights = []
    for i in range(NTABLE):
        w = tables[str(i)]
        if len(w) != NTAP or sum(w) != 512:
            raise SystemExit(f"表 {i} 不合法: {len(w)} 个,和 {sum(w)}")
        weights.extend(int(v) for v in w)

    flat_lut = []
    for code in range(NCODE):
        idx, dx, dy = (int(v) for v in lut[code][:3])
        if not (0 <= idx < NTABLE) or abs(dx) != 1 or abs(dy) != 1:
            raise SystemExit(f"LUT[{code}] = {(idx, dx, dy)} 越界")
        flat_lut.extend((idx, dx, dy))

    text = HEADER % {
        "ntap": NTAP, "ntable": NTABLE, "ncode": NCODE,
        "weights": rows(weights, NTAP, 5),
        "lut": rows(flat_lut, 24, 3),
    }
    path = os.path.abspath(OUT)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"{NTABLE} 张表 x {NTAP} tap + {NCODE} 项 LUT -> {path}")


if __name__ == "__main__":
    main()
